# Generated by Django 5.0.1 on 2024-01-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
