# Generated by Django 5.0.1 on 2024-01-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avater',
            new_name='avatar',
        ),
    ]
